### ISSUE TITLE
SQL Server issues with Boolean columns (.Select fails, .Where fails)

### ISSUE THREAD

**Issue by Shaddix** [ethanli83/EFSqlTranslator#30]

**Comment by ethanli83** [comment]
Hi @Shaddix,

Many thanks for fixing the issue. Just a small thing, as the value of a bit type column will be 1. 0 or null, it maybe better to do 
```
return (bool)Val ? 1 : 0;
```

also, if you have time, do you mind to checkout how it would behave if the column is a nullable bool?

thanks again!

**Comment by ethanli83** [comment]
hi @Shaddix,

I have pushed out a new version of the package which contains your fix. 

I made a class called PostgresQlConstant to handle the boolean type value specially. It will use the keywords TRUE and FALSE instead of '1' and '0'. Then, for other db, it will just 1 and 0.

I also made it supports following usages:
```
db.Comments
    .Where(c => !c.IsDeleted)
    .Select(c => new
    {
        NotDeleted = !c.IsDeleted
    });
```

Let me know if you have any problem.  Also, thanks again for the pull request~
